EXAMPLE_STATES = [
    "I still don't have a great hygiene of life. I continue to sleep only about 6 hours a night due to work constraints. I still smoke a lot and haven't been able to cut down.  I have started eating more fruits and vegetables with my meals, although processed food still makes up a significant portion of my diet. I now take a short walk daily for 15-20 minutes. I've tried short guided meditations a few times this week. I'm making a conscious effort to drink more water throughout the day. I also dedicate 15-20 minutes daily to relaxing activities like listening to music or reading.\n",
    "I still don't have a great hygiene of life. I continue to sleep only about 6 hours a night due to work constraints. I still smoke a lot. I continue to eat more fruits and vegetables with my meals, although processed food still makes up a significant portion of my diet. I take a short walk daily for 15-20 minutes. I practice short guided meditations a few times a week.  I make a conscious effort to drink more water throughout the day. I dedicate 15-20 minutes daily to relaxing activities like listening to music or reading.\n",
    "I still don't have a great hygiene of life. I continue to sleep only about 6 hours a night due to work constraints. I still smoke a lot. I continue to eat fruits and vegetables with my meals, although processed food still makes up a significant portion of my diet. I take a short walk daily for 15-20 minutes. I practice short guided meditations a few times a week. I make a conscious effort to drink more water throughout the day. I dedicate 15-20 minutes daily to relaxing activities like listening to music or reading.\n",
    "I still don't have a great hygiene of life. I continue to sleep only about 6 hours a night due to work constraints. I still smoke a lot. I continue to eat fruits and vegetables with my meals, while processed food still makes up a significant portion of my diet.  I take a short walk daily for 15-20 minutes. I practice short guided meditations a few times a week. I make a conscious effort to drink more water throughout the day. I dedicate 15-20 minutes daily to relaxing activities like listening to music or reading.\n",
    "I still don't have a great hygiene of life. I continue to sleep only about 6 hours a night due to work constraints. I still smoke a lot. I continue to eat fruits and vegetables with my meals, while processed food still makes up a significant portion of my diet. I take a short walk daily for 15-20 minutes. I practice short guided meditations a few times a week.  I make a conscious effort to drink more water throughout the day. I dedicate 15-20 minutes daily to relaxing activities like listening to music or reading.\n",
    "I still don't have a great hygiene of life. I continue to sleep only about 6 hours a night due to work constraints. I still smoke a lot. I continue to eat fruits and vegetables with my meals, while processed food still makes up a significant portion of my diet.  I take a short walk daily for 15-20 minutes. I practice short guided meditations a few times a week. I make a conscious effort to drink more water throughout the day. I dedicate 15-20 minutes daily to relaxing activities like listening to music or reading.\n",
    "I still don't have a great hygiene of life. I continue to sleep only about 6 hours a night due to work constraints. I still smoke a lot. I continue to eat fruits and vegetables with my meals, while processed food still makes up a significant portion of my diet. I take a short walk daily for 15-20 minutes. I practice short guided meditations a few times a week.  I make a conscious effort to drink more water throughout the day. I dedicate 15-20 minutes daily to relaxing activities like listening to music or reading.\n",
    "I still don't have a great hygiene of life. I continue to sleep only about 6 hours a night due to work constraints. I still smoke a lot. I continue to eat fruits and vegetables with my meals, while processed food still makes up a significant portion of my diet. I take a short walk daily for 15-20 minutes.  I practice short guided meditations a few times a week and dedicate 15-20 minutes daily to relaxing activities like listening to music or reading. I make a conscious effort to drink more water throughout the day.\n",
    "I still don't have a great hygiene of life. I continue to sleep only about 6 hours a night due to work constraints. I still smoke a lot. I continue to eat fruits and vegetables with my meals, while processed food still makes up a significant portion of my diet. I take a short walk daily for 15-20 minutes. I practice short guided meditations a few times a week and dedicate 15-20 minutes daily to relaxing activities like listening to music or reading. I make a conscious effort to drink more water throughout the day.\n",
    "I still don't have a great hygiene of life. I continue to sleep only about 6 hours a night due to work constraints. I still smoke a lot. I continue to eat fruits and vegetables with my meals, while processed food still makes up a significant portion of my diet. I take a short walk daily for 15-20 minutes.  I practice short guided meditations a few times a week and dedicate 15-20 minutes daily to relaxing activities like listening to music or reading. I make a conscious effort to drink more water throughout the day.\n",
]

EXAMPLE_STATES_2 = [
    "I maintain good overall hygiene. I continue to prioritize hydration, drinking plenty of water daily. My sleep schedule remains consistent, sleeping from 10 p.m. to 6 a.m., which allows me to feel quite well-rested.  I now incorporate a short run once a week in addition to my three gym sessions.  I am beginning to incorporate more whole foods into my diet, alongside some processed meals. I've also started practicing short mindfulness exercises a few times a week.  I'm motivated to continue these positive changes.\n",
    "I maintain good overall hygiene. I prioritize hydration, drinking plenty of water daily. My sleep schedule remains consistent, sleeping from 10 p.m. to 6 a.m., which allows me to feel well-rested. I incorporate a short run once a week in addition to my three gym sessions. I continue to incorporate more whole foods into my diet, alongside some processed meals.  I practice short mindfulness exercises a few times a week. I remain motivated to continue these positive changes.\n",
    "I maintain good overall hygiene. I prioritize hydration, drinking plenty of water daily. My sleep schedule remains consistent, sleeping from 10 p.m. to 6 a.m., which allows me to feel well-rested.  I continue to incorporate more whole foods into my diet, alongside some processed meals. I incorporate a short run once a week in addition to my three gym sessions. I practice short mindfulness exercises a few times a week. I remain motivated to continue these positive changes.\n",
    "I maintain good overall hygiene. I prioritize hydration, drinking plenty of water daily. My sleep schedule remains consistent, sleeping from 10 p.m. to 6 a.m., which allows me to feel well-rested. I continue to incorporate more whole foods into my diet, alongside some processed meals.  I incorporate a short run once a week in addition to my three gym sessions. I practice short mindfulness exercises a few times a week. I remain motivated to continue these positive changes.\n",
    "I maintain good overall hygiene. I prioritize hydration, drinking plenty of water daily. My sleep schedule remains consistent, sleeping from 10 p.m. to 6 a.m., which allows me to feel well-rested. I continue to incorporate more whole foods into my diet, alongside some processed meals. I incorporate a short run once a week and three gym sessions. I practice short mindfulness exercises a few times a week. I remain motivated to continue these positive changes.\n",
    "I maintain good overall hygiene. I prioritize hydration, drinking plenty of water daily. My sleep schedule remains consistent, sleeping from 10 p.m. to 6 a.m., which allows me to feel well-rested. I continue to incorporate more whole foods into my diet, alongside some processed meals.  I incorporate a short run once a week and three gym sessions. I practice short mindfulness exercises a few times a week. I remain motivated to continue these positive changes.\n",
    "I maintain good overall hygiene. I prioritize hydration, drinking plenty of water daily. My sleep schedule remains consistent, sleeping from 10 p.m. to 6 a.m., which allows me to feel well-rested. I continue to incorporate more whole foods into my diet, alongside some processed meals. I incorporate a short run once a week and three gym sessions. I practice short mindfulness exercises a few times a week. I remain motivated to continue these positive changes.\n",
    "I maintain good overall hygiene. I prioritize hydration, drinking plenty of water daily. My sleep schedule remains consistent, sleeping from 10 p.m. to 6 a.m., which allows me to feel well-rested. I continue to incorporate more whole foods into my diet, alongside some processed meals. I incorporate a short run once a week and three gym sessions. I practice short mindfulness exercises a few times a week. I remain motivated to continue these positive changes.\n",
    "I maintain good overall hygiene. I prioritize hydration, drinking plenty of water daily. My sleep schedule remains consistent, sleeping from 10 p.m. to 6 a.m., which allows me to feel well-rested. I continue to incorporate more whole foods into my diet, alongside some processed meals. I incorporate a short run once a week and three gym sessions. I practice short mindfulness exercises a few times a week. I remain motivated to continue these positive changes.\n",
    "I maintain good overall hygiene. I prioritize hydration, drinking plenty of water daily. My sleep schedule remains consistent, sleeping from 10 p.m. to 6 a.m., which allows me to feel well-rested. I continue to incorporate more whole foods into my diet, alongside some processed meals.  I incorporate a short run once a week and three gym sessions. I practice short mindfulness exercises a few times a week. I remain motivated to continue these positive changes.\n",
    "I maintain good overall hygiene. I prioritize hydration, drinking plenty of water daily. My sleep schedule remains consistent, sleeping from 10 p.m. to 6 a.m., allowing me to feel well-rested. I continue to incorporate more whole foods into my diet, alongside some processed meals. I incorporate a short run once a week and three gym sessions. I practice short mindfulness exercises a few times a week. I remain motivated to continue these positive changes.\n",
    "I maintain good overall hygiene. I prioritize hydration, drinking plenty of water daily. My sleep schedule is consistent, sleeping from 10 p.m. to 6 a.m., which leaves me feeling well-rested. I continue to incorporate more whole foods into my diet, alongside some processed meals.  I incorporate a short run once a week and three gym sessions. I practice short mindfulness exercises a few times a week. I remain motivated to continue these positive changes.\n",
    "I maintain good overall hygiene. I prioritize hydration, drinking plenty of water daily. My sleep schedule is consistent, sleeping from 10 p.m. to 6 a.m., which leaves me feeling well-rested. I continue to incorporate more whole foods into my diet, alongside some processed meals. I incorporate a short run once a week and three gym sessions. I practice short mindfulness exercises a few times a week. I remain motivated to continue these positive changes.\n",
    "I maintain good overall hygiene. I prioritize hydration, drinking plenty of water daily. I maintain a consistent sleep schedule, sleeping from 10 p.m. to 6 a.m., which leaves me feeling well-rested. I continue to incorporate more whole foods into my diet, alongside some processed meals.  I incorporate a short run once a week and three gym sessions. I practice short mindfulness exercises a few times a week. I remain motivated to continue these positive changes.\n",
    "I maintain good overall hygiene. I prioritize hydration, drinking plenty of water daily. I maintain a consistent sleep schedule, sleeping from 10 p.m. to 6 a.m., which leaves me feeling well-rested. I continue to incorporate more whole foods into my diet, alongside some processed meals. I incorporate a short run once a week and three gym sessions. I practice short mindfulness exercises a few times a week. I remain motivated to continue these positive changes.\n",
]

EXAMPLE_ACTIONS_2 = [
    {
        "Sleep": "I maintain my current sleep schedule of 10 p.m. to 6 a.m.",
        "Diet": "I start replacing some of my processed meals with whole food options, like adding a salad to my dinner or having fruit for a snack.",
        "Exercise": "I continue going to the gym 3 times a week and add one short run to my weekly routine.",
        "Smoking": "I do not have any information on that category",
        "Alcohol": "I do not have any information on that category",
        "Social relationships": "I do not have any information on that category",
        "Mental health": "I try a short mindfulness exercise, like a 5-minute guided meditation, a few times this week.",
        "Motivation": "none",
        "Hydration": "I continue drinking plenty of water throughout the day.",
        "Stress management": "none",
        "Screen time": "I do not have any information on that category",
    },
    {
        "Sleep": "I maintain a consistent sleep schedule of 10 p.m. to 6 a.m.",
        "Diet": "I continue to incorporate more whole foods into my diet alongside some processed meals.",
        "Exercise": "I continue my routine of three gym sessions and one short run per week.",
        "Smoking": "I do not have any information on that category",
        "Alcohol": "I do not have any information on that category",
        "Social relationships": "I do not have any information on that category",
        "Mental health": "I practice short mindfulness exercises a few times a week.",
        "Motivation": "I maintain my motivation to continue these positive changes.",
        "Hydration": "I drink plenty of water daily.",
        "Stress management": "I do not have any information on that category",
        "Screen time": "I do not have any information on that category",
    },
    {
        "Sleep": "I maintain a consistent sleep schedule of 10 p.m. to 6 a.m.",
        "Diet": "I continue incorporating more whole foods into my diet alongside some processed meals.",
        "Exercise": "I continue my routine of three gym sessions and a weekly short run.",
        "Smoking": "I do not have any information on that category",
        "Alcohol": "I do not have any information on that category",
        "Social relationships": "I do not have any information on that category",
        "Mental health": "I practice short mindfulness exercises a few times a week.",
        "Motivation": "I remain motivated to continue my positive changes.",
        "Hydration": "I prioritize hydration by drinking plenty of water daily.",
        "Stress management": "I do not have any information on that category",
        "Screen time": "I do not have any information on that category",
    },
    {
        "Sleep": "I maintain a consistent sleep schedule of 10 p.m. to 6 a.m.",
        "Diet": "I continue incorporating more whole foods into my diet alongside some processed meals.",
        "Exercise": "I continue my routine of three gym sessions and a short run weekly.",
        "Smoking": "I do not have any information on that category",
        "Alcohol": "I do not have any information on that category",
        "Social relationships": "I do not have any information on that category",
        "Mental health": "I practice short mindfulness exercises a few times a week.",
        "Motivation": "I remain motivated to continue my positive changes.",
        "Hydration": "I prioritize hydration by drinking plenty of water daily.",
        "Stress management": "I do not have any information on that category",
        "Screen time": "I do not have any information on that category",
    },
    {
        "Sleep": "I maintain a consistent sleep schedule, sleeping from 10 p.m. to 6 a.m.",
        "Diet": "I continue to incorporate more whole foods into my diet alongside some processed meals.",
        "Exercise": "I incorporate a short run once a week and three gym sessions.",
        "Smoking": "I do not have any information on that category",
        "Alcohol": "I do not have any information on that category",
        "Social relationships": "I do not have any information on that category",
        "Mental health": "I practice short mindfulness exercises a few times a week.",
        "Motivation": "I remain motivated to continue these positive changes.",
        "Hydration": "I prioritize hydration, drinking plenty of water daily.",
        "Stress management": "I do not have any information on that category",
        "Screen time": "I do not have any information on that category",
    },
    {
        "Sleep": "I maintain a consistent sleep schedule of 10 p.m. to 6 a.m.",
        "Diet": "I continue incorporating more whole foods into my diet alongside some processed meals.",
        "Exercise": "I continue my routine of a short run once a week and three gym sessions.",
        "Smoking": "I do not have any information on that category",
        "Alcohol": "I do not have any information on that category",
        "Social relationships": "I do not have any information on that category",
        "Mental health": "I practice short mindfulness exercises a few times a week.",
        "Motivation": "I remain motivated to continue my positive changes.",
        "Hydration": "I drink plenty of water daily.",
        "Stress management": "I do not have any information on that category",
        "Screen time": "I do not have any information on that category",
    },
    {
        "Sleep": "I maintain a consistent sleep schedule of 10 p.m. to 6 a.m.",
        "Diet": "I continue incorporating more whole foods into my diet alongside some processed meals.",
        "Exercise": "I continue my routine of a short run once a week and three gym sessions.",
        "Smoking": "I do not have any information on that category",
        "Alcohol": "I do not have any information on that category",
        "Social relationships": "I do not have any information on that category",
        "Mental health": "I practice short mindfulness exercises a few times a week.",
        "Motivation": "I remain motivated to continue my positive changes.",
        "Hydration": "I prioritize hydration by drinking plenty of water daily.",
        "Stress management": "I do not have any information on that category",
        "Screen time": "I do not have any information on that category",
    },
    {
        "Sleep": "I maintain a consistent sleep schedule of 10 p.m. to 6 a.m.",
        "Diet": "I continue incorporating more whole foods into my diet alongside some processed meals.",
        "Exercise": "I continue my routine of a short run once a week and three gym sessions.",
        "Smoking": "I do not have any information on that category",
        "Alcohol": "I do not have any information on that category",
        "Social relationships": "I do not have any information on that category",
        "Mental health": "I practice short mindfulness exercises a few times a week.",
        "Motivation": "I remain motivated to continue my positive changes.",
        "Hydration": "I prioritize hydration by drinking plenty of water daily.",
        "Stress management": "I do not have any information on that category",
        "Screen time": "I do not have any information on that category",
    },
    {
        "Sleep": "I maintain a consistent sleep schedule of 10 p.m. to 6 a.m.",
        "Diet": "I continue incorporating more whole foods into my diet alongside some processed meals.",
        "Exercise": "I continue my routine of a short run once a week and three gym sessions.",
        "Smoking": "I do not have any information on that category",
        "Alcohol": "I do not have any information on that category",
        "Social relationships": "I do not have any information on that category",
        "Mental health": "I practice short mindfulness exercises a few times a week.",
        "Motivation": "I remain motivated to continue my positive changes.",
        "Hydration": "I prioritize hydration by drinking plenty of water daily.",
        "Stress management": "I do not have any information on that category",
        "Screen time": "I do not have any information on that category",
    },
    {
        "Sleep": "I maintain a consistent sleep schedule of 10 p.m. to 6 a.m.",
        "Diet": "I continue incorporating more whole foods into my diet alongside some processed meals.",
        "Exercise": "I go for a short run once a week and attend three gym sessions.",
        "Smoking": "I do not have any information on that category",
        "Alcohol": "I do not have any information on that category",
        "Social relationships": "I do not have any information on that category",
        "Mental health": "I practice short mindfulness exercises a few times a week.",
        "Motivation": "I remain motivated to continue my positive changes.",
        "Hydration": "I drink plenty of water daily.",
        "Stress management": "I do not have any information on that category",
        "Screen time": "I do not have any information on that category",
    },
    {
        "Sleep": "I maintain a consistent sleep schedule of 10 p.m. to 6 a.m.",
        "Diet": "I continue incorporating more whole foods into my diet alongside some processed meals.",
        "Exercise": "I continue my routine of a short run once a week and three gym sessions.",
        "Smoking": "I do not have any information on that category",
        "Alcohol": "I do not have any information on that category",
        "Social relationships": "I do not have any information on that category",
        "Mental health": "I practice short mindfulness exercises a few times a week.",
        "Motivation": "I remain motivated to continue my positive changes.",
        "Hydration": "I prioritize hydration by drinking plenty of water daily.",
        "Stress management": "I do not have any information on that category",
        "Screen time": "I do not have any information on that category",
    },
    {
        "Sleep": "I maintain a consistent sleep schedule of 10 p.m. to 6 a.m.",
        "Diet": "I continue incorporating more whole foods into my diet alongside some processed meals.",
        "Exercise": "I continue my routine of a short run once a week and three gym sessions.",
        "Smoking": "I do not have any information on that category",
        "Alcohol": "I do not have any information on that category",
        "Social relationships": "I do not have any information on that category",
        "Mental health": "I practice short mindfulness exercises a few times a week.",
        "Motivation": "I remain motivated to continue my positive changes.",
        "Hydration": "I prioritize hydration by drinking plenty of water daily.",
        "Stress management": "I do not have any information on that category",
        "Screen time": "I do not have any information on that category",
    },
    {
        "Sleep": "I maintain a consistent sleep schedule of 10 p.m. to 6 a.m.",
        "Diet": "I continue incorporating more whole foods into my diet alongside some processed meals.",
        "Exercise": "I continue my routine of a short run once a week and three gym sessions.",
        "Smoking": "I do not have any information on that category",
        "Alcohol": "I do not have any information on that category",
        "Social relationships": "I do not have any information on that category",
        "Mental health": "I practice short mindfulness exercises a few times a week.",
        "Motivation": "I remain motivated to continue my positive changes.",
        "Hydration": "I drink plenty of water daily.",
        "Stress management": "I do not have any information on that category",
        "Screen time": "I do not have any information on that category",
    },
    {
        "Sleep": "I maintain a consistent sleep schedule of 10 p.m. to 6 a.m.",
        "Diet": "I continue incorporating more whole foods into my diet alongside some processed meals.",
        "Exercise": "I go for a short run once a week and attend three gym sessions.",
        "Smoking": "I do not have any information on that category",
        "Alcohol": "I do not have any information on that category",
        "Social relationships": "I do not have any information on that category",
        "Mental health": "I practice short mindfulness exercises a few times a week.",
        "Motivation": "I remain motivated to continue these positive changes.",
        "Hydration": "I drink plenty of water daily.",
        "Stress management": "I do not have any information on that category",
        "Screen time": "I do not have any information on that category",
    },
    {
        "Sleep": "I maintain a consistent sleep schedule, sleeping from 10 p.m. to 6 a.m.",
        "Diet": "I continue to incorporate more whole foods into my diet, alongside some processed meals.",
        "Exercise": "I incorporate a short run once a week and three gym sessions.",
        "Smoking": "I do not have any information on that category",
        "Alcohol": "I do not have any information on that category",
        "Social relationships": "I do not have any information on that category",
        "Mental health": "I practice short mindfulness exercises a few times a week.",
        "Motivation": "I remain motivated to continue these positive changes.",
        "Hydration": "I prioritize hydration, drinking plenty of water daily.",
        "Stress management": "I do not have any information on that category",
        "Screen time": "I do not have any information on that category",
    },
]
